name: Build
on:
  pull_request: {}

jobs:
  build:
	runs-on: ubuntu:latest
	name: Build
	steps:
	- uses: actions/checkout@v2
	- name: Setup go 
	  uses: actions/setup-go@v2
	  with:
		go-version: 1.16
	  - name: Install gojen
	  run: go install github.com/Hunter-Thompson/gojen
	  - name: Run gojen
	    run: gojen