name: Release
on:
  push:
	branches:
	  - master

jobs:
  build:
    runs-on: ubuntu:latest
    name: Release
    steps:
    - uses: actions/checkout@v2
    - name: Setup go 
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
	  - name: Install gojen
      run: go install github.com/Hunter-Thompson/gojen
	  - name: Run gojen
	    run: gojen 
  release:
    needs:
    - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: go-semantic-release/action@v1
        id: semrel
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          changelog-generator-opt: "emojis=false"
          force-bump-patch-version: true