on:
  push:
    branches:
    - master
name: Release
jobs:
  build:
    strategy:
      matrix:
        go-version: [1.17]
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run:  go build && gojen
    - name: build and run gojen
      run: "go build && ./gojen"
  release:
    needs:
    - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: go-semantic-release/action@v1
        id: semrel
        with:
          github-token: ${{ secrets.GIT_TOKEN }}
          changelog-generator-opt: "emojis=false"
          force-bump-patch-version: true