"on":
  release:
    types:
    - published
name: Upload Binary
jobs:
  upload-binary:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Upload binary
      uses: wangyoucao577/go-release-action@v1.19
      with:
        github_token: ${{ secrets.GIT_TOKEN }}
        goarch: amd64
        goos: linux
        goversion: "1.17"
    name: upload binary
